# Example Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: demo-kustomization

namespace: demo-app

commonLabels:
  managed-by: kustomize

commonAnnotations:
  created-at: '2025-12-18'

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

replicas:
  - name: demo-app
    count: 1

patchesStrategicMerge:
  - patch-replicas.yaml
